In [1]:
import pandas as pd
import numpy as np

In [2]:
url="https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
!wget -q $url -O List_of_postal_codes_of_Canada.html
print("Download complete")

Download complete

In [3]:
df = pd.read_html(url)[0]
df.shape

(287, 3)

In [4]:
df.where(cond=df['Borough']!='Not assigned',inplace=True)
df.dropna(inplace=True)
df.head()

  Postcode           Borough     Neighbourhood
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M6A        North York  Lawrence Heights
6      M6A        North York    Lawrence Manor

In [5]:
df['Neighbourhood']=np.where(df['Neighbourhood']=='Not assigned',df['Borough'],df['Neighbourhood'])
df[df['Neighbourhood']==df['Borough']]

  Postcode       Borough Neighbourhood
9      M9A  Queen's Park  Queen's Park

In [6]:
df=df.groupby(['Postcode','Borough'])['Neighbourhood'].apply(','.join).reset_index()
df.head()

  Postcode      Borough                         Neighbourhood
0      M1B  Scarborough                         Rouge,Malvern
1      M1C  Scarborough  Highland Creek,Rouge Hill,Port Union
2      M1E  Scarborough       Guildwood,Morningside,West Hill
3      M1G  Scarborough                                Woburn
4      M1H  Scarborough                             Cedarbrae

In [7]:
df.shape

(103, 3)

In [8]:
!wget -q "https://cocl.us/Geospatial_data" -O Geospatial_data.csv
print("Download complete")

Download complete

In [9]:
df_geo = pd.read_csv('Geospatial_data.csv')
df_geo.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [11]:
df=df.merge(df_geo,how='right',left_on='Postcode',right_on='Postal Code',validate='one_to_one')
df.drop(columns=['Postal Code'],inplace=True)
df.head()

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge,Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek,Rouge Hill,Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood,Morningside,West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476