In [1]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /opt/conda/envs/Python36/lib/python3.6/site-packages (4.7.1)
Requirement already satisfied: soupsieve>=1.2 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from beautifulsoup4) (1.7.1)

In [2]:
!pip install lxml

Requirement already satisfied: lxml in /opt/conda/envs/Python36/lib/python3.6/site-packages (4.3.1)

In [3]:
!pip install html5lib

Requirement already satisfied: html5lib in /opt/conda/envs/Python36/lib/python3.6/site-packages (1.0.1)
Requirement already satisfied: webencodings in /opt/conda/envs/Python36/lib/python3.6/site-packages (from html5lib) (0.5.1)
Requirement already satisfied: six>=1.9 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from html5lib) (1.12.0)

In [31]:
import pandas as pd
import numpy as np

In [2]:
url="https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
!wget $url -O List_of_postal_codes_of_Canada.html

--2020-01-15 10:18:27--  https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M
Resolving en.wikipedia.org (en.wikipedia.org)... 208.80.154.224, 2620:0:861:ed1a::1
Connecting to en.wikipedia.org (en.wikipedia.org)|208.80.154.224|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 78805 (77K) [text/html]
Saving to: ‘List_of_postal_codes_of_Canada.html’

100%[======================================>] 78,805       440KB/s   in 0.2s

2020-01-15 10:18:28 (440 KB/s) - ‘List_of_postal_codes_of_Canada.html’ saved [78805/78805]

In [34]:
df = pd.read_html(url)[0]
df.shape

(287, 3)

In [35]:
df.where(cond=df['Borough']!='Not assigned',inplace=True)
df.dropna(inplace=True)
df.head()

  Postcode           Borough     Neighbourhood
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M6A        North York  Lawrence Heights
6      M6A        North York    Lawrence Manor

In [38]:
df['Neighbourhood']=np.where(df['Neighbourhood']=='Not assigned',df['Borough'],df['Neighbourhood'])
df[df['Neighbourhood']==df['Borough']]

   Postcode       Borough Neighbourhood
93      M9A  Queen's Park  Queen's Park

In [40]:
df=df.groupby(['Postcode','Borough'])['Neighbourhood'].apply(','.join).reset_index()
df.head()

(103, 3)

In [15]:
df.shape

  Postcode                         Neighbourhood
0      M1B                         Rouge,Malvern
1      M1C  Highland Creek,Rouge Hill,Port Union
2      M1E       Guildwood,Morningside,West Hill
3      M1G                                Woburn
4      M1H                             Cedarbrae