### Import all necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Download requered data from wikipage

In [2]:
url="https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
!wget $url -O List_of_postal_codes_of_Canada.html

--2020-01-15 11:26:34--  https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M
Resolving en.wikipedia.org (en.wikipedia.org)... 208.80.154.224, 2620:0:861:ed1a::1
Connecting to en.wikipedia.org (en.wikipedia.org)|208.80.154.224|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘List_of_postal_codes_of_Canada.html’

    [ <=>                                   ] 78,805       431KB/s   in 0.2s

2020-01-15 11:26:34 (431 KB/s) - ‘List_of_postal_codes_of_Canada.html’ saved [78805]

### Transform the data into a pandas dataframe

In [3]:
df = pd.read_html(url)[0]
df.shape

(287, 3)

### Only process the cells that have an assigned borough. Ignore cells with a [Borough] that is 'Not assigned'.

In [4]:
df.where(cond=df['Borough']!='Not assigned',inplace=True)
df.dropna(inplace=True)
df.head()

  Postcode           Borough     Neighbourhood
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M6A        North York  Lawrence Heights
6      M6A        North York    Lawrence Manor

### If a cell has a [Borough] but a 'Not assigned' [Neighbourhood], then the [Neighbourhood] will be the same as the [Borough]

In [5]:
df['Neighbourhood']=np.where(df['Neighbourhood']=='Not assigned',df['Borough'],df['Neighbourhood'])
df[df['Neighbourhood']==df['Borough']]

  Postcode       Borough Neighbourhood
9      M9A  Queen's Park  Queen's Park

### More than one Neighbourhood can exist in one postal code area

In [9]:
df=df.groupby(['Postcode','Borough'])['Neighbourhood'].apply(','.join).reset_index()
df.head(9)

  Postcode      Borough                                  Neighbourhood
0      M1B  Scarborough                                  Rouge,Malvern
1      M1C  Scarborough           Highland Creek,Rouge Hill,Port Union
2      M1E  Scarborough                Guildwood,Morningside,West Hill
3      M1G  Scarborough                                         Woburn
4      M1H  Scarborough                                      Cedarbrae
5      M1J  Scarborough                            Scarborough Village
6      M1K  Scarborough      East Birchmount Park,Ionview,Kennedy Park
7      M1L  Scarborough                  Clairlea,Golden Mile,Oakridge
8      M1M  Scarborough  Cliffcrest,Cliffside,Scarborough Village West

In [7]:
df.shape

(103, 3)