In [87]:
import pandas as pd
import numpy as np

In [47]:
!wget --cookies=on --save-cookies cookies.txt --keep-session-cookies --post-data 'user=razinkov@hotmail.com&password=nMNbKWe2uf4YHQZ' 'https://www.ctt.pt/fecas/login?service=https%3A%2F%2Fwww.ctt.pt%2Ffemgu%2Fj_spring_cas_security_check.jspx'
!wget --cookies=on --load-cookies cookies.txt --keep-session-cookies 'https://www.ctt.pt/feapl_2/app/restricted/postalCodeSearch/postalCodeDownloadFiles!downloadPostalCodeFile.jspx' -O PostCodeFull.Pt.zip

--2020-01-21 14:09:44--  https://www.ctt.pt/fecas/login?service=https%3A%2F%2Fwww.ctt.pt%2Ffemgu%2Fj_spring_cas_security_check.jspx
Resolving www.ctt.pt (www.ctt.pt)... 62.28.56.1
Connecting to www.ctt.pt (www.ctt.pt)|62.28.56.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘login?service=https:%2F%2Fwww.ctt.pt%2Ffemgu%2Fj_spring_cas_security_check.jspx.1’

    [  <=>                                  ] 112,846      444KB/s   in 0.2s

2020-01-21 14:09:46 (444 KB/s) - ‘login?service=https:%2F%2Fwww.ctt.pt%2Ffemgu%2Fj_spring_cas_security_check.jspx.1’ saved [112846]

--2020-01-21 14:09:47--  https://www.ctt.pt/feapl_2/app/restricted/postalCodeSearch/postalCodeDownloadFiles!downloadPostalCodeFile.jspx
Resolving www.ctt.pt (www.ctt.pt)... 62.28.56.1
Connecting to www.ctt.pt (www.ctt.pt)|62.28.56.1|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.ctt.pt/fecas/login?service=https%3A%2F%2Fwww.ctt.pt%2Ffeapl_2%2Fj_spring_cas_security_check.jspx%3Bjsessionid%3DSopYbsDBIvC71oiRRNHF4w__.si_part6_node1 [following]
--2020-01-21 14:09:47--  https://www.ctt.pt/fecas/login?service=https%3A%2F%2Fwww.ctt.pt%2Ffeapl_2%2Fj_spring_cas_security_check.jspx%3Bjsessionid%3DSopYbsDBIvC71oiRRNHF4w__.si_part6_node1
Reusing existing connection to www.ctt.pt:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘PostCodeFull.Pt.zip’

    [  <=>                                  ] 111,959      406KB/s   in 0.3s

2020-01-21 14:09:48 (406 KB/s) - ‘PostCodeFull.Pt.zip’ saved [111959]

In [49]:
!rm -f login*
!ls -la

total 124
drwxr-x--- 2 dsxuser dsxuser   4096 Jan 21 14:11 .
drwx------ 1 dsxuser dsxuser   4096 Jan 21 12:15 ..
-rw-r----- 1 dsxuser dsxuser    180 Jan 21 14:09 cookies.txt
-rw-r----- 1 dsxuser dsxuser 111959 Jan 21 14:09 PostCodeFull.Pt.zip

In [38]:
!unzip -x todos_cp.zip

unzip:  cannot find or open todos_cp.zip, todos_cp.zip.zip or todos_cp.zip.ZIP.

In [48]:
!cat cookies.txt

# HTTP cookie file.
# Generated by Wget on 2020-01-21 14:09:46.
# Edit at your own risk.

www.ctt.pt	FALSE	/fecas	TRUE	0	JSESSIONID	AFDC23F325DBA1172F145E6296C58969.si_part3_node1

In [139]:
# @hidden_cell
# The following code contains the credentials for a file in your IBM Cloud Object Storage.
# You might want to remove those credentials before you share your notebook.
credentials_CC = {
    'IAM_SERVICE_ID': 'iam-ServiceId-c718bc9c-6715-41c4-a090-ef49d30cf02e',
    'IBM_API_KEY_ID': 'nEAwnadbTDR7sZjg2dsuEPEqMP3WU1UFgh7WLkkMZppS',
    'ENDPOINT': 'https://s3.eu-geo.objectstorage.service.networklayer.com',
    'IBM_AUTH_ENDPOINT': 'https://iam.eu-gb.bluemix.net/oidc/token',
    'BUCKET': 'capstoneprojectthebattleofneighbo-donotdelete-pr-rpev4qjyoaz4ga'
}

SyntaxError: invalid syntax (<ipython-input-139-b291a3536da2>, line 4)

In [53]:
from ibm_botocore.client import Config
import ibm_boto3
cos = ibm_boto3.client(service_name='s3',
    ibm_api_key_id=credentials['IBM_API_KEY_ID'],
    ibm_service_instance_id=credentials['IAM_SERVICE_ID'],
    ibm_auth_endpoint=credentials['IBM_AUTH_ENDPOINT'],
    config=Config(signature_version='oauth'),
    endpoint_url=credentials['ENDPOINT'])

In [71]:
from ibm_botocore.client import Config
import ibm_boto3
def download_file_cos(credentials,local_file_name,key):  
    cos = ibm_boto3.client(service_name='s3',
    ibm_api_key_id=credentials['IBM_API_KEY_ID'],
    ibm_service_instance_id=credentials['IAM_SERVICE_ID'],
    ibm_auth_endpoint=credentials['IBM_AUTH_ENDPOINT'],
    config=Config(signature_version='oauth'),
    endpoint_url=credentials['ENDPOINT'])
    try:
        res=cos.download_file(Bucket=credentials['BUCKET'],Key=key,Filename=local_file_name)
    except Exception as e:
        print(Exception, e)
    else:
        print('File Downloaded')

In [120]:
download_file_cos(credentials,'concelhos.txt','concelhos.txt')
download_file_cos(credentials,'distritos.txt','distritos.txt')
download_file_cos(credentials,'todos_cp.txt','todos_cp.txt')

File Downloaded
File Downloaded
File Downloaded

In [118]:
!ls -la

total 26316
drwxr-x--- 2 dsxuser dsxuser     4096 Jan 21 16:12 .
drwx------ 1 dsxuser dsxuser     4096 Jan 21 12:15 ..
-rw-r----- 1 dsxuser dsxuser     5690 Jan 21 16:12 concelhos.txt
-rw-r----- 1 dsxuser dsxuser      180 Jan 21 14:09 cookies.txt
-rw-r----- 1 dsxuser dsxuser      446 Jan 21 16:12 distritos.txt
-rw-r----- 1 dsxuser dsxuser   111959 Jan 21 14:09 PostCodeFull.Pt.zip
-rw-r----- 1 dsxuser dsxuser 26807486 Jan 21 16:12 todos_cp.txt

In [137]:
df_CC=pd.read_csv('concelhos.txt',sep=';',encoding='iso8859_15')
df_CC[df_CC['DD']==3]

    DD  CC                   DESIG
33   3   6               Esposende
34   3   7                    Fafe
35   3   8               Guimarães
36   3   9        Póvoa de Lanhoso
37   3  10         Terras de Bouro
38   3  11         Vieira do Minho
39   3  12  Vila Nova de Famalicão
40   3  13              Vila Verde
41   3  14                  Vizela
42   3   1                  Amares
43   3   2                Barcelos
44   3   3                   Braga
45   3   4     Cabeceiras de Basto
46   3   5       Celorico de Basto

In [122]:
df_DD=pd.read_csv('distritos.txt',sep=';',encoding='iso8859_15')
df_DD.head()

   DD           DESIG
0   1          Aveiro
1   2            Beja
2   3           Braga
3   4        Bragança
4   5  Castelo Branco

In [123]:
#columns_1={'DD','CC','LLLL','LOCALIDADE','ART_COD','ART_TIPO','PRI_PREP','ART_TITULO','SEG_PREP','ART_DESIG','ART_LOCAL','TROÇO','PORTA','CLIENTE','CP4','CP3','CPALF'}
#columns_2=['DD','CC','LLLL','LOCALIDADE','ART_COD','ART_TIPO','PRI_PREP','ART_TITULO','SEG_PREP','ART_DESIG','ART_LOCAL','TROÇO','PORTA','CLIENTE','CP4','CP3','CPALF']
df_PostalCode=pd.read_csv('todos_cp.txt',sep=';',encoding='iso8859_15')
#df_PostalCode=pd.read_csv('todos_cp.txt',sep=';',encoding='latin-1',header=None,names=columns_1,usecols=columns_1)[columns_1]
df_PostalCode.shape

(326077, 17)

In [124]:
df_PostalCode.head()

,DD,CC,LLLL,LOCALIDADE,ART_COD,ART_TIPO,PRI_PREP,ART_TITULO,SEG_PREP,ART_DESIG,ART_LOCAL,TROÇO,PORTA,CLIENTE,CP4,CP3,CPALF
0,1,1,249,Alcafaz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,11,AGADÃO
1,1,1,250,Caselho,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,12,AGADÃO
2,1,1,251,Corga da Serra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,13,AGADÃO
3,1,1,252,Foz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,14,AGADÃO
4,1,1,253,Guistola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3750,15,AGADÃO

In [125]:
df_PostalCode=df_PostalCode[['DD','CC','LLLL','LOCALIDADE','CP4','CP3','CPALF']]
df_PostalCode.head()

   DD  CC  LLLL      LOCALIDADE   CP4  CP3   CPALF
0   1   1   249         Alcafaz  3750   11  AGADÃO
1   1   1   250         Caselho  3750   12  AGADÃO
2   1   1   251  Corga da Serra  3750   13  AGADÃO
3   1   1   252             Foz  3750   14  AGADÃO
4   1   1   253        Guistola  3750   15  AGADÃO

In [126]:
df_PostalCode.shape

(326077, 7)

In [127]:
!pip install geocoder

Collecting geocoder
  Downloading https://files.pythonhosted.org/packages/4f/6b/13166c909ad2f2d76b929a4227c952630ebaf0d729f6317eb09cbceccbab/geocoder-1.38.1-py2.py3-none-any.whl (98kB)
     |████████████████████████████████| 102kB 7.3MB/s ta 0:00:011
Requirement already satisfied: six in /opt/conda/envs/Python36/lib/python3.6/site-packages (from geocoder) (1.12.0)
Requirement already satisfied: click in /opt/conda/envs/Python36/lib/python3.6/site-packages (from geocoder) (7.0)
Requirement already satisfied: requests in /opt/conda/envs/Python36/lib/python3.6/site-packages (from geocoder) (2.21.0)
Requirement already satisfied: future in /opt/conda/envs/Python36/lib/python3.6/site-packages (from geocoder) (0.17.1)
Collecting ratelim (from geocoder)
  Downloading https://files.pythonhosted.org/packages/f2/98/7e6d147fd16a10a5f821db6e25f192265d6ecca3d82957a4fdd592cad49c/ratelim-0.1.6-py2.py3-none-any.whl
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->geocoder) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->geocoder) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->geocoder) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/Python36/lib/python3.6/site-packages (from requests->geocoder) (2019.11.28)
Requirement already satisfied: decorator in /opt/conda/envs/Python36/lib/python3.6/site-packages (from ratelim->geocoder) (4.3.2)
Installing collected packages: ratelim, geocoder
Successfully installed geocoder-1.38.1 ratelim-0.1.6

In [144]:
from geopy.geocoders import Nominatim
import requests
import geopy
geopy.geocoders.options.default_user_agent = "my-application"

In [147]:
geolocator = Nominatim()
address = 'Faro, Portugal'
geolocator = Nominatim()
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude

print(latitude)
print(longitude)

37.0162727
-7.9351771

In [141]:
# @hidden_cell
CLIENT_ID='SMSYPRW3UME43CU2SOU5IJT0P52JY0HZ4RJP0VQM1H4A1BB1'
CLIENT_SECRET='TTWDTJNW1K24SDZJS4A5LZKBHOKZ2LDJOOITQKBVPLRFNKPN'
VERSION='20200121'

In [148]:
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET,
    VERSION,
    latitude,
    longitude,
    100,
    10)
url

'https://api.foursquare.com/v2/venues/explore?&client_id=SMSYPRW3UME43CU2SOU5IJT0P52JY0HZ4RJP0VQM1H4A1BB1&client_secret=TTWDTJNW1K24SDZJS4A5LZKBHOKZ2LDJOOITQKBVPLRFNKPN&v=20200121&ll=37.0162727,-7.9351771&radius=100&limit=10'

In [149]:
results = requests.get(url).json()

In [150]:
results

{'meta': {'code': 200, 'requestId': '5e273349d03993001b6a5b37'},
 'response': {'suggestedFilters': {'header': 'Tap to show:',
   'filters': [{'name': 'Open now', 'key': 'openNow'}]},
  'headerLocation': 'Faro',
  'headerFullLocation': 'Faro',
  'headerLocationGranularity': 'city',
  'totalResults': 11,
  'suggestedBounds': {'ne': {'lat': 37.017172700900005,
    'lng': -7.934052040046277},
   'sw': {'lat': 37.0153726991, 'lng': -7.936302159953723}},
  'groups': [{'type': 'Recommended Places',
    'name': 'recommended',
    'items': [{'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4c647074f07e2d7f8f418f50',
       'name': 'Columbus',
       'location': {'address': 'Praça Dom Francisco Gomes, nº 13',
        'lat': 37.01547227576279,
        'lng': -7.934938866750873,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.01547227576279,
          'lng': -7.934938866750873}],
        'distance': 91,
        'postalCode': '8000',
        'cc': 'PT',
        'city': 'Faro',
        'state': 'Algarve',
        'country': 'Portugal',
        'formattedAddress': ['Praça Dom Francisco Gomes, nº 13',
         '8000 Faro',
         'Portugal']},
       'categories': [{'id': '4bf58dd8d48988d121941735',
         'name': 'Lounge',
         'pluralName': 'Lounges',
         'shortName': 'Lounge',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/default_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4c647074f07e2d7f8f418f50-0'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '573878b1498ec301c87495f3',
       'name': 'The Woods',
       'location': {'lat': 37.01663151733155,
        'lng': -7.9355512908367825,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.01663151733155,
          'lng': -7.9355512908367825}],
        'distance': 51,
        'cc': 'PT',
        'city': 'Faro',
        'state': 'Algarve',
        'country': 'Portugal',
        'formattedAddress': ['Faro', 'Portugal']},
       'categories': [{'id': '4bf58dd8d48988d112941735',
         'name': 'Juice Bar',
         'pluralName': 'Juice Bars',
         'shortName': 'Juice Bar',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/juicebar_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-573878b1498ec301c87495f3-1'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '589a1ea0a8b7597bcf469925',
       'name': 'Ground 864',
       'location': {'address': 'Travessa José Coelho, 2',
        'lat': 37.017142,
        'lng': -7.93527,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.017142,
          'lng': -7.93527}],
        'distance': 97,
        'cc': 'PT',
        'city': 'Faro',
        'state': 'Algarve',
        'country': 'Portugal',
        'formattedAddress': ['Travessa José Coelho, 2', 'Faro', 'Portugal']},
       'categories': [{'id': '56aa371ce4b08b9a8d57356c',
         'name': 'Beer Bar',
         'pluralName': 'Beer Bars',
         'shortName': 'Beer Bar',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/pub_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-589a1ea0a8b7597bcf469925-2'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '5124bfc6011c31466485d9e7',
       'name': 'Se7e Pedras',
       'location': {'address': 'Travessa José Coelho, 2',
        'lat': 37.017123338045984,
        'lng': -7.935441431489104,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.017123338045984,
          'lng': -7.935441431489104}],
        'distance': 97,
        'postalCode': '8000-470',
        'cc': 'PT',
        'city': 'Faro',
        'state': 'Algarve',
        'country': 'Portugal',
        'formattedAddress': ['Travessa José Coelho, 2',
         '8000-470 Faro',
         'Portugal']},
       'categories': [{'id': '4bf58dd8d48988d123941735',
         'name': 'Wine Bar',
         'pluralName': 'Wine Bars',
         'shortName': 'Wine Bar',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/winery_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-5124bfc6011c31466485d9e7-3'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '57f91777498edf8f0a535c81',
       'name': 'Padaria Urbana',
       'location': {'address': 'R. Conselheiro Bivar 6',
        'lat': 37.016666,
        'lng': -7.935235,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.016666,
          'lng': -7.935235}],
        'distance': 44,
        'postalCode': '8000-078',
        'cc': 'PT',
        'city': 'Faro',
        'state': 'Algarve',
        'country': 'Portugal',
        'formattedAddress': ['R. Conselheiro Bivar 6',
         '8000-078 Faro',
         'Portugal']},
       'categories': [{'id': '4bf58dd8d48988d16a941735',
         'name': 'Bakery',
         'pluralName': 'Bakeries',
         'shortName': 'Bakery',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/bakery_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-57f91777498edf8f0a535c81-4'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '5351396e498e737b6d3ab554',
       'name': 'Hamburgeria da Baixa',
       'location': {'address': 'R. Conselheiro Bívar',
        'lat': 37.016746,
        'lng': -7.935278,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.016746,
          'lng': -7.935278}],
        'distance': 53,
        'postalCode': '8000',
        'cc': 'PT',
        'city': 'Faro',
        'state': 'Algarve',
        'country': 'Portugal',
        'formattedAddress': ['R. Conselheiro Bívar', '8000 Faro', 'Portugal']},
       'categories': [{'id': '4bf58dd8d48988d16c941735',
         'name': 'Burger Joint',
         'pluralName': 'Burger Joints',
         'shortName': 'Burgers',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/burger_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-5351396e498e737b6d3ab554-5'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4bcf6f840ffdce721779b2c0',
       'name': 'Hotel Faro',
       'location': {'address': 'Praça Dom Francisco Gomes, 2',
        'lat': 37.01637251194909,
        'lng': -7.934903518511397,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.01637251194909,
          'lng': -7.934903518511397}],
        'distance': 26,
        'postalCode': '8000-168',
        'cc': 'PT',
        'city': 'Faro',
        'state': 'Algarve',
        'country': 'Portugal',
        'formattedAddress': ['Praça Dom Francisco Gomes, 2',
         '8000-168 Faro',
         'Portugal']},
       'categories': [{'id': '4bf58dd8d48988d1fa931735',
         'name': 'Hotel',
         'pluralName': 'Hotels',
         'shortName': 'Hotel',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/travel/hotel_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []},
       'venuePage': {'id': '38583186'}},
      'referralId': 'e-0-4bcf6f840ffdce721779b2c0-6'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '579d09b4498e9ffc5f5f3b76',
       'name': 'Café Cervejaria Aliança',
       'location': {'lat': 37.01610078925618,
        'lng': -7.9345911212448925,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.01610078925618,
          'lng': -7.9345911212448925}],
        'distance': 55,
        'cc': 'PT',
        'city': 'Faro',
        'state': 'Algarve',
        'country': 'Portugal',
        'formattedAddress': ['Faro', 'Portugal']},
       'categories': [{'id': '50327c8591d4c4b30a586d5d',
         'name': 'Brewery',
         'pluralName': 'Breweries',
         'shortName': 'Brewery',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/brewery_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-579d09b4498e9ffc5f5f3b76-7'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4d274928dbc160fc639441b6',
       'name': 'Restaurante Ria Formosa',
       'location': {'address': 'Praça Dom Francisco Gomes N2',
        'lat': 37.016436878742454,
        'lng': -7.934862179068883,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.016436878742454,
          'lng': -7.934862179068883}],
        'distance': 33,
        'postalCode': '8000 168',
        'cc': 'PT',
        'city': 'Faro',
        'state': 'Algarve',
        'country': 'Portugal',
        'formattedAddress': ['Praça Dom Francisco Gomes N2',
         '8000 168 Faro',
         'Portugal']},
       'categories': [{'id': '4def73e84765ae376e57713a',
         'name': 'Portuguese Restaurant',
         'pluralName': 'Portuguese Restaurants',
         'shortName': 'Portuguese',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/portuguese_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []},
       'venuePage': {'id': '38583187'}},
      'referralId': 'e-0-4d274928dbc160fc639441b6-8'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '55b8f3ce498edb41f8c6ec39',
       'name': 'Bohéme',
       'location': {'address': 'Avenida da República, 2',
        'lat': 37.01658402565113,
        'lng': -7.935424158500784,
        'labeledLatLngs': [{'label': 'display',
          'lat': 37.01658402565113,
          'lng': -7.935424158500784}],
        'distance': 41,
        'postalCode': '8000-079',
        'cc': 'PT',
        'city': 'Faro',
        'state': 'Algarve',
        'country': 'Portugal',
        'formattedAddress': ['Avenida da República, 2',
         '8000-079 Faro',
         'Portugal']},
       'categories': [{'id': '56aa371ce4b08b9a8d57356c',
         'name': 'Beer Bar',
         'pluralName': 'Beer Bars',
         'shortName': 'Beer Bar',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/nightlife/pub_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-55b8f3ce498edb41f8c6ec39-9'}]}]}}